add_test([=[JuniorDeveloperTest.ConstructorInitializesCorrectly]=]  /workspaces/Programmentwurf/junior_tests [==[--gtest_filter=JuniorDeveloperTest.ConstructorInitializesCorrectly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuniorDeveloperTest.ConstructorInitializesCorrectly]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[JuniorDeveloperTest.LoadLogoValidFile]=]  /workspaces/Programmentwurf/junior_tests [==[--gtest_filter=JuniorDeveloperTest.LoadLogoValidFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuniorDeveloperTest.LoadLogoValidFile]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[JuniorDeveloperTest.LoadLogoInvalidFileThrows]=]  /workspaces/Programmentwurf/junior_tests [==[--gtest_filter=JuniorDeveloperTest.LoadLogoInvalidFileThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuniorDeveloperTest.LoadLogoInvalidFileThrows]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[JuniorDeveloperTest.LoadLogoEmptyFilenameThrows]=]  /workspaces/Programmentwurf/junior_tests [==[--gtest_filter=JuniorDeveloperTest.LoadLogoEmptyFilenameThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuniorDeveloperTest.LoadLogoEmptyFilenameThrows]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  junior_tests_TESTS JuniorDeveloperTest.ConstructorInitializesCorrectly JuniorDeveloperTest.LoadLogoValidFile JuniorDeveloperTest.LoadLogoInvalidFileThrows JuniorDeveloperTest.LoadLogoEmptyFilenameThrows)
