add_test([=[SeniorDeveloperTest.ConstructorInitializesCorrectly]=]  /workspaces/Programmentwurf/senior_tests [==[--gtest_filter=SeniorDeveloperTest.ConstructorInitializesCorrectly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SeniorDeveloperTest.ConstructorInitializesCorrectly]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SeniorDeveloperTest.LoadLogoValidFile]=]  /workspaces/Programmentwurf/senior_tests [==[--gtest_filter=SeniorDeveloperTest.LoadLogoValidFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SeniorDeveloperTest.LoadLogoValidFile]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SeniorDeveloperTest.LoadLogoInvalidFileThrows]=]  /workspaces/Programmentwurf/senior_tests [==[--gtest_filter=SeniorDeveloperTest.LoadLogoInvalidFileThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SeniorDeveloperTest.LoadLogoInvalidFileThrows]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SeniorDeveloperTest.LoadLogoEmptyFilenameThrows]=]  /workspaces/Programmentwurf/senior_tests [==[--gtest_filter=SeniorDeveloperTest.LoadLogoEmptyFilenameThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SeniorDeveloperTest.LoadLogoEmptyFilenameThrows]=]  PROPERTIES WORKING_DIRECTORY /workspaces/Programmentwurf SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  senior_tests_TESTS SeniorDeveloperTest.ConstructorInitializesCorrectly SeniorDeveloperTest.LoadLogoValidFile SeniorDeveloperTest.LoadLogoInvalidFileThrows SeniorDeveloperTest.LoadLogoEmptyFilenameThrows)
